language: node_js

node_js:
  - 0.10.40

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam
  - npm install -g coffee-script@1.8.0
  - npm install -g https://github.com/serut/spacejam/tarball/master coveralls codecov.io
  - npm install -g eslint

script:
  - spacejam test-packages ./ --coverage || spacejam test-packages ./  --loglevel debug # if it fails, I want to see how tests fail without coverage
  - cat lcov.info | coveralls || true # ignore coveralls error
  - cat lcov.info  | codecov || true # ignore codecov error
  - eslint . || true # ignore eslint error
