language: node_js

node_js:
  - 0.10.43
  - 4.4.7

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor - Keep in mind that you need
  # to remove your travis cache to get meteor updates
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install dependencies
  - npm install https://github.com/serut/spacejam/tarball/windows-suppport-rc4 coveralls codecov.io
  - npm install -g eslint

script:
  - mkdir .coverage
  - spacejam test-packages ./ --coverage out_lcovonly --driver-package practicalmeteor:mocha-console-runner
  - cat .coverage/lcov.info | coveralls || cat .coverage/lcov.info || true # ignore coveralls error
  - cat .coverage/lcov.info | codecov || cat .coverage/lcov.info || true # ignore codecov error
  - eslint . || true # ignore eslint error
