

language: node_js
node_js:
  - 0.10.43
  - 4
cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

 before_install:
  # Download Meteor - Keep in mind that you need
  # to remove your travis cache to get meteor updates
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install dependencies
  - npm install https://github.com/serut/spacejam/tarball/windows-suppport-rc4 coveralls codecov.io
  - npm install -g eslint

script:
  - spacejam test-packages ./ --coverage out_lcovonly || spacejam test-packages ./  --loglevel debug # if it fails, I want to see how tests fail without coverage
  - cat lcov.info | coveralls || true # ignore coveralls error
  - cat lcov.info | codecov || true # ignore codecov error
  - eslint . || true # ignore eslint error
